/*
 * Filename  main.cpp
 * Date      03/20/2020
 * Author    Jerry Huynh
 * Email     jsh170830@utdallas.edu
 * Course    CS 3377.501 Spring 2020
 * Version   1.0
 * Copyright 2020, All Rights Reserved
 * 
 * Description:
 *
 *	Call the yylex() function generated by flex.
 */

#include <stdio.h>             /* needed for printf() */
#include "program4.h"         /* needed for ENUM */


/* 
 * Manually insert prototype and extern declarations for the
 * stuff in the flex output file.
 */
int yylex(void);
extern char *yytext;


/* Just call the lexical scanner until we reach EOF */

int main()
{
  printf ("\nOperating in scan mode\n\n");

  int token;
  
  token = yylex();

  while(token != 0)
    {
      switch(token)
	    {
		    case NAME_INITIAL_TOKEN:
	  	    printf("yylex returned NAME_INITIAL_TOKEN token (%s)\n", yytext);
        break;
        case ROMANTOKEN:
	  	    printf("yylex returned ROMANTOKEN token (%d)\n", token);
        break;
        case SRTOKEN:
	  	    printf("yylex returned SRTOKEN token (%s)\n", yytext);
        break;
        case JRTOKEN:
	  	    printf("yylex returned JRTOKEN token (%s)\n", yytext);
        break;
        case HASHTOKEN:
	  	    printf("yylex returned HASHTOKEN token (%d)\n", token);
        break;
        case COMMATOKEN:
	  	    printf("yylex returned COMMATOKEN token (%d)\n", token);
        break;
        case EOLTOKEN:
	  	    printf("yylex returned EOLTOKEN token (%d)\n", token);
        break;
        case DASHTOKEN:
	  	    printf("yylex returned DASHTOKEN token (%d)\n", token);
        break;
        case INTTOKEN:
	  	    printf("yylex returned INTTOKEN token (%s)\n", yytext);
        break;
        case NAMETOKEN:
	  	    printf("yylex returned NAMETOKEN token (%s)\n", yytext);
        break;
        case IDENTIFIERTOKEN:
	  	    printf("yylex returned IDENTIFIERTOKEN token (%s)\n", yytext);
        break;
		    default:
	  		  printf("UNKNOWN\n");
	}

      token = yylex();
    }
  
  printf("Done\n");
  return 0;
}
